name: Build package

on: [ push, pull_request, workflow_dispatch ]

jobs:
  build_pkg:
    runs-on: ubuntu-22.04
    container: pspdev/pspdev:latest
    steps:

    - name: Checkout
      uses: actions/checkout@v4
    
    - name: Install dependencies
      run: |
        apk add zip git

    - name: Checkout dbglogger
      uses: actions/checkout@v4
      with:
        repository: bucanero/dbglogger
        path: dbglogger

    - name: Install dbglogger
      working-directory: dbglogger
      run: |
        make -f Makefile.psp install

    - name: Recompile wolfssl
      run: |
        git clone --depth 1 -b v5.7.0-stable https://github.com/wolfSSL/wolfssl
        cd wolfssl
        mkdir build && cd build
        CFLAGS="-DNO_WRITEV" \
          cmake -DCMAKE_TOOLCHAIN_FILE=$PSPDEV/psp/share/pspdev.cmake \
          -DCMAKE_BUILD_TYPE=RelWithDebInfo \
          -DBUILD_SHARED_LIBS=OFF \
          -DWOLFSSL_CRYPT_TESTS=OFF -DWOLFSSL_EXAMPLES=OFF -DWOLFSSL_OPENSSLEXTRA=ON -DWARNING_C_FLAGS=-w \
          ..
        make -j $(getconf _NPROCESSORS_ONLN) clean
        make -j $(getconf _NPROCESSORS_ONLN)
        make -j $(getconf _NPROCESSORS_ONLN) install
      
    - name: Recompile curl with WolfSSL
      run: |
        git clone --depth 1 -b curl-8_7_1 https://github.com/curl/curl
        cd curl
        mkdir build && cd build
        cmake -DCMAKE_TOOLCHAIN_FILE=$PSPDEV/psp/share/pspdev.cmake \
          -DCMAKE_BUILD_TYPE=RelWithDebInfo \
          -DBUILD_SHARED_LIBS=OFF \
          -DENABLE_THREADED_RESOLVER=OFF -DCURL_USE_OPENSSL=OFF -DCURL_USE_WOLFSSL=ON -DCURL_DISABLE_SOCKETPAIR=ON -DHAVE_BASENAME=NO -DHAVE_ATOMIC=NO -DENABLE_WEBSOCKETS=ON -DENABLE_IPV6=OFF -DCURL_USE_LIBPSL=OFF -DCURL_USE_LIBSSH2=OFF \
          ..
        make -j $(getconf _NPROCESSORS_ONLN) clean
        make -j $(getconf _NPROCESSORS_ONLN)
        make -j $(getconf _NPROCESSORS_ONLN) install
  
    - name: Build PKGi App Package (OFW)
      run: |
        mkdir ofw && cd ofw
        psp-cmake .. -DCMAKE_BUILD_TYPE=Release -DBUILD_PRX=ON -DENC_PRX=ON
        make
        make createzip

    - name: Build PKGi App Package
      run: |
        psp-cmake . -DCMAKE_BUILD_TYPE=Release
        make
        make createzip
    
    - name: Get short SHA
      id: slug
      run: |
        printf '%s\n' "sha8=$(printf '%s\n' ${GITHUB_SHA} | cut -c1-8)" >> $GITHUB_OUTPUT

    - name: Push package artifact
      uses: actions/upload-artifact@v4
      with:
        name: pkgi-psp-build_${{ steps.slug.outputs.sha8 }}
        path: pkgi-psp.zip
        if-no-files-found: error

    - name: Push OFW artifact
      uses: actions/upload-artifact@v4
      with:
        name: pkgi-ofw-build_${{ steps.slug.outputs.sha8 }}
        path: ofw/pkgi-psp.zip
